### get /ping
GET http://localhost:8080/ping
Content-Type: application/json

### POST /tasks
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "description": "some description"
}


### GET /tasks/:id
GET http://localhost:8080/tasks/588783ac-fac7-41d9-ba3b-959c7c097b3b
Content-Type: application/json

{
    "newDescription": "new description"
}